import { image, video } from './media';
import type { HelpTutorial } from './types';

export const EVENT_TUTORIALS: HelpTutorial[] = [
    {
        id: 'criar-evento',
        category: 'eventos',
        title: 'Publicar um evento',
        summary: 'Do título ao cartaz: o evento fica na agenda do site com página e link próprios.',
        minutes: 4,
        audience: 'direcao',
        tab: 'events',
        featured: true,
        keywords: ['evento', 'agenda', 'novo evento', 'cartaz', 'rascunho', 'publicar', 'destaque', 'torneio', 'data', 'local'],
        media: [image('eventos-lista', 'Lista de eventos do backoffice com pesquisa, filtros e ações')],
        steps: [
            { text: 'Abra "Eventos" e carregue em "Novo evento".', tip: 'Tem pouco tempo? "Criar com IA" preenche o formulário a partir de uma frase.' },
            { text: 'Preencha "Título", "Categoria", "Data" e "Local".' },
            { text: 'Escreva a "Descrição do evento". O botão "Melhorar" corrige e arruma o texto com IA.' },
            { text: 'Em "Cartaz ou imagem", escolha "Carregar", "Colar link" ou "Gerar com IA".' },
            { text: 'Se quiser o evento na página inicial, marque "Mostrar em destaque na página inicial". Para torneios, marque "É um torneio" e indique a modalidade.' },
            { text: 'Em "Estado", escolha "Publicado" para aparecer já no site, ou "Rascunho" para continuar mais tarde.', tip: 'Os rascunhos ficam invisíveis no site.' },
            { text: 'Carregue em "Guardar".' },
        ],
    },
    {
        id: 'abrir-inscricoes',
        category: 'eventos',
        title: 'Receber inscrições num evento',
        summary: 'Lugares, preço, perguntas extra e inscrição sem conta para quem chega pelo WhatsApp.',
        minutes: 3,
        audience: 'direcao',
        tab: 'events',
        relatedTabs: ['registrations'],
        keywords: ['inscrições', 'aceitar inscrições', 'lotação', 'lugares', 'preço', 'perguntas extra', 'sem conta', 'esgotado', 'formulário'],
        media: [image('evento-inscricoes', 'Secção de inscrições do formulário de evento com lugares, preço e perguntas extra')],
        steps: [
            { text: 'Abra o evento em "Eventos" (Editar) e marque "Aceitar inscrições pelo site".' },
            { text: 'Em "Lugares disponíveis" indique a lotação. Vazio quer dizer sem limite; quando enche, o site mostra "Esgotado".' },
            { text: 'Em "Preço por pessoa (€)" indique o valor, ou deixe vazio se for grátis.', tip: 'O site não cobra: o pagamento combina-se com a organização, no local ou pelos contactos.' },
            { text: 'Deixe desligado "Só sócios com conta se podem inscrever": assim qualquer pessoa se inscreve só com nome e email.' },
            { text: 'Precisa de saber mais? Em "Perguntas extra", carregue em "Acrescentar pergunta" (por exemplo, nome da equipa ou tamanho da t-shirt).' },
            { text: 'Carregue em "Guardar" e partilhe o evento a partir do site.' },
        ],
    },
    {
        id: 'gerir-inscricoes',
        category: 'eventos',
        title: 'Confirmar inscrições e preparar a porta',
        summary: 'Confirmar de uma vez, lista para a porta, exportar para Excel e copiar emails.',
        minutes: 3,
        audience: 'direcao',
        tab: 'registrations',
        featured: true,
        keywords: ['inscrições', 'confirmar', 'confirmar pendentes', 'cancelar', 'lista para a porta', 'imprimir', 'excel', 'exportar', 'copiar emails', 'bcc', 'lotação'],
        media: [
            video('confirmar-inscricoes', 'No separador Inscrições escolhe-se o evento, vê-se quantas inscrições estão por confirmar, confirma-se uma inscrição com o botão Confirmar e depois aparecem os botões Lista para a porta, Exportar (Excel) e Copiar emails.'),
            image('inscricoes', 'Separador Inscrições com o evento escolhido, contadores e botões de ação'),
        ],
        steps: [
            { text: 'Abra "Inscrições" e escolha o evento em "Evento". Por omissão aparece o próximo evento com inscrições abertas.' },
            { text: 'Veja os números: por confirmar, confirmadas, canceladas e a lotação.' },
            { text: 'Carregue em "Confirmar pendentes" para confirmar todas de uma vez, ou use "Confirmar" e "Cancelar" em cada linha.', tip: 'Cancelar liberta o lugar. Uma inscrição cancelada pode voltar com "Reativar".' },
            { text: 'No dia, carregue em "Lista para a porta": abre uma lista por ordem alfabética pronta a imprimir, sem as canceladas.' },
            { text: '"Exportar (Excel)" descarrega a lista com as respostas às perguntas extra; abre no Excel ou no Google Sheets.' },
            { text: '"Copiar emails" copia os emails de quem vem. Cole-os no campo Bcc de um email para avisar todos sem mostrar os endereços.', warning: 'Use sempre Bcc: pôr os emails em "Para" mostra-os a todos os participantes.' },
        ],
    },
    {
        id: 'partilhar-evento',
        category: 'eventos',
        title: 'Partilhar um evento no WhatsApp e no Facebook',
        summary: 'Cada evento tem o seu link; quem o abre vê o cartaz e inscreve-se logo.',
        minutes: 2,
        audience: 'direcao',
        tab: 'events',
        keywords: ['partilhar', 'whatsapp', 'facebook', 'link', 'divulgar', 'redes sociais'],
        steps: [
            { text: 'Abra o evento no site (Eventos, depois "Ver e inscrever-me").' },
            { text: 'Use os botões "WhatsApp", "Facebook" ou "Copiar link".' },
            { text: 'No WhatsApp, envie para o grupo da associação: a mensagem leva o título, a data e o link.' },
            { text: 'Quem carrega no link abre aquele evento e inscreve-se só com nome e email.' },
        ],
    },
];
