import { image, video } from './media';
import type { HelpTutorial } from './types';

export const EVENT_TUTORIALS: HelpTutorial[] = [
    {
        id: 'criar-evento',
        category: 'eventos',
        title: 'Publicar um evento',
        summary: 'Do título ao cartaz: o evento fica na agenda do site com página e link próprios.',
        recap: '**Eventos** › **Novo evento**, preencha o essencial, escolha **Publicado** e carregue em **Guardar**.',
        minutes: 4,
        audience: 'direcao',
        tab: 'events',
        featured: true,
        related: ['abrir-inscricoes', 'criar-com-ia', 'partilhar-evento'],
        keywords: ['evento', 'agenda', 'novo evento', 'cartaz', 'rascunho', 'publicar', 'destaque', 'torneio', 'data', 'local'],
        media: [image('eventos-lista', 'Lista de eventos do backoffice com pesquisa, filtros e ações')],
        steps: [
            { text: 'Abra **Eventos** e carregue em **Novo evento**.', tip: 'Tem pouco tempo? **Criar com IA** preenche o formulário a partir de uma frase.' },
            { text: 'Preencha **Título**, **Categoria**, **Data** e **Local**.' },
            { text: 'Escreva a **Descrição do evento**.', tip: 'O botão **Melhorar** corrige e arruma o texto com IA.' },
            { text: 'Em **Cartaz ou imagem**, escolha **Carregar**, **Colar link** ou **Gerar com IA**.' },
            { text: 'Para o pôr na página inicial, marque **Mostrar em destaque na página inicial**.', tip: 'Para torneios, marque **É um torneio** e indique a modalidade.' },
            { text: 'Em **Estado**, escolha **Publicado** para aparecer já, ou **Rascunho** para acabar mais tarde.', why: 'Os rascunhos não aparecem no site: pode prepará-los com calma.' },
            { text: 'Carregue em **Guardar**.' },
        ],
    },
    {
        id: 'abrir-inscricoes',
        category: 'eventos',
        title: 'Receber inscrições num evento',
        summary: 'Lugares, preço, perguntas extra e inscrição sem conta para quem chega pelo WhatsApp.',
        recap: 'No evento, marque **Aceitar inscrições pelo site**, indique lugares e preço e carregue em **Guardar**.',
        minutes: 3,
        audience: 'direcao',
        tab: 'events',
        relatedTabs: ['registrations'],
        related: ['gerir-inscricoes', 'partilhar-evento', 'rgpd-basico'],
        keywords: ['inscrições', 'aceitar inscrições', 'lotação', 'lugares', 'preço', 'perguntas extra', 'sem conta', 'esgotado', 'formulário'],
        media: [image('evento-inscricoes', 'Secção de inscrições do formulário de evento com lugares, preço e perguntas extra')],
        steps: [
            { text: 'Em **Eventos**, carregue em **Editar** no evento.' },
            { text: 'Marque **Aceitar inscrições pelo site**.' },
            { text: 'Em **Lugares disponíveis**, indique a lotação. Vazio quer dizer sem limite.', why: 'Quando os lugares acabam, o site mostra **Esgotado** e não aceita mais inscrições.' },
            { text: 'Em **Preço por pessoa (€)**, indique o valor. Deixe vazio se for grátis.', tip: 'O site não cobra: o pagamento combina-se com a organização.' },
            { text: 'Deixe desligado **Só sócios com conta se podem inscrever**.', why: 'Assim qualquer pessoa se inscreve só com nome e email, mesmo sem conta.' },
            { text: 'Precisa de saber mais? Em **Perguntas extra**, carregue em **Acrescentar pergunta**.', tip: 'Por exemplo: nome da equipa ou tamanho da t-shirt.' },
            { text: 'Carregue em **Guardar** e partilhe o evento a partir do site.' },
        ],
    },
    {
        id: 'gerir-inscricoes',
        category: 'eventos',
        title: 'Confirmar inscrições e preparar a porta',
        summary: 'Confirmar de uma vez, lista para a porta, exportar para Excel e copiar emails.',
        recap: 'Em **Inscrições**, escolha o evento, carregue em **Confirmar pendentes** e, no dia, em **Lista para a porta**.',
        minutes: 3,
        audience: 'direcao',
        tab: 'registrations',
        featured: true,
        related: ['abrir-inscricoes', 'rgpd-basico', 'resolver-problemas'],
        keywords: ['inscrições', 'confirmar', 'confirmar pendentes', 'por confirmar', 'cancelar', 'lista para a porta', 'imprimir', 'excel', 'exportar', 'copiar emails', 'bcc', 'lotação'],
        media: [
            video('confirmar-inscricoes', 'No separador Inscrições escolhe-se o evento, vê-se quantas inscrições estão por confirmar, confirma-se uma inscrição com o botão Confirmar e depois aparecem os botões Lista para a porta, Exportar (Excel) e Copiar emails.'),
            image('inscricoes', 'Separador Inscrições com o evento escolhido, contadores e botões de ação'),
        ],
        steps: [
            { text: 'Abra **Inscrições** e escolha o evento em **Evento**.', tip: 'Por omissão aparece o próximo evento com inscrições abertas.' },
            { text: 'Veja os números: por confirmar, confirmadas, canceladas e a lotação.' },
            { text: 'Carregue em **Confirmar pendentes** para confirmar todas de uma vez.', tip: 'Também pode usar **Confirmar** ou **Cancelar** em cada linha.' },
            { text: 'Alguém desistiu? Carregue em **Cancelar** nessa linha.', why: 'Cancelar liberta o lugar. Se for engano, **Reativar** volta a pôr a inscrição.' },
            { text: 'No dia, carregue em **Lista para a porta** e imprima.', why: 'A lista vem por ordem alfabética e sem as inscrições canceladas.' },
            { text: 'Para guardar ou partilhar com a equipa, carregue em **Exportar (Excel)**.', tip: 'O ficheiro abre no Excel ou no Google Sheets e leva as respostas às perguntas extra.' },
            { text: 'Para avisar todos, carregue em **Copiar emails** e cole no campo Bcc de um email.', warning: 'Use sempre Bcc: pôr os emails em "Para" mostra-os a todos os participantes.' },
        ],
    },
    {
        id: 'partilhar-evento',
        category: 'eventos',
        title: 'Partilhar um evento no WhatsApp e no Facebook',
        summary: 'Cada evento tem o seu link; quem o abre vê o cartaz e inscreve-se logo.',
        recap: 'Abra o evento no site e use **WhatsApp**, **Facebook** ou **Copiar link**.',
        minutes: 2,
        audience: 'direcao',
        tab: 'events',
        related: ['partilhar-redes', 'abrir-inscricoes'],
        keywords: ['partilhar', 'whatsapp', 'facebook', 'link', 'divulgar', 'redes sociais', 'copiar link'],
        steps: [
            { text: 'No site, abra **Eventos** e carregue em **Ver e inscrever-me** no evento.', tip: 'Sem inscrições abertas, o botão chama-se **Ver detalhes**.' },
            { text: 'Carregue em **WhatsApp**, **Facebook** ou **Copiar link**.', tip: 'No telemóvel aparece também **Mais**, com as outras apps.' },
            { text: 'No WhatsApp, escolha o grupo da associação e envie.', why: 'A mensagem já leva o título, a data, o local e o link.' },
            { text: 'Quem carregar no link abre o evento e inscreve-se só com nome e email.' },
        ],
    },
];
