import { image, video } from './media';
import type { HelpTutorial } from './types';

export const MEMBER_TUTORIALS: HelpTutorial[] = [
    {
        id: 'socios-quotas',
        category: 'socios',
        title: 'Registar sócios e marcar quotas pagas',
        summary: 'O número de sócio e o ano da quota que cada sócio vê na sua área.',
        recap: '**Sócios & Quotas** › **Adicionar sócio** com o email da conta; atualize **Quota paga até** a cada pagamento.',
        minutes: 3,
        audience: 'direcao',
        tab: 'member-quotas',
        related: ['dar-acesso', 'contactos-pagamentos', 'avisos-socios'],
        keywords: ['sócios', 'quotas', 'quota paga', 'número de sócio', 'atrasada', 'em dia', 'pagamento', 'cartão de sócio'],
        media: [image('socios-quotas', 'Separador Sócios & Quotas com a lista de sócios, o número e o estado da quota')],
        steps: [
            { text: 'Abra **Sócios & Quotas** e carregue em **Adicionar sócio**.' },
            { text: 'Em **Email**, escreva o email com que o sócio entra no site.', warning: 'Tem de ser exatamente o email da conta, ou o sócio não vê o número nem a quota.' },
            { text: 'Preencha o **Nº Sócio**.' },
            { text: 'Em **Quota paga até**, escreva o último ano pago, por exemplo 2026.' },
            { text: 'Use **Notas** para o que for útil à direção, como "pagou em dinheiro".', why: 'O sócio não vê as notas: são só para a direção.' },
            { text: 'Carregue em **Guardar**.' },
            { text: 'Recebeu um pagamento? Edite o sócio e atualize o ano.', tip: 'Os filtros **Em dia**, **Atrasada** e **Sem ano** mostram logo quem tem quotas por pagar.' },
        ],
    },
    {
        id: 'documentos-socios',
        category: 'socios',
        title: 'Partilhar documentos com os sócios',
        summary: 'Estatutos, atas e regulamentos na área de sócio.',
        recap: 'Copie o link de partilha do PDF e cole-o em **Documentos** › **Novo documento**.',
        minutes: 2,
        audience: 'direcao',
        tab: 'documents',
        related: ['avisos-socios', 'socios-quotas'],
        keywords: ['documentos', 'atas', 'estatutos', 'regulamentos', 'relatórios', 'pdf', 'ficheiro'],
        steps: [
            { text: 'Guarde o PDF no Google Drive ou no OneDrive e copie o link de partilha.' },
            { text: 'Abra **Documentos** e carregue em **Novo documento**.' },
            { text: 'Preencha o **Título** e escolha a **Categoria**: Atas, Relatórios, Estatutos, Regulamentos ou Outros.' },
            { text: 'Cole o link em **Link do ficheiro** e carregue em **Guardar**.', tip: 'O documento aparece aos sócios em **Documentos**, na área de sócio.' },
            { text: 'Abra o link numa janela anónima do browser para o testar.', why: 'Se pedir autorização, os sócios também não o conseguem abrir.' },
        ],
    },
    {
        id: 'avisos-socios',
        category: 'socios',
        title: 'Enviar um aviso aos sócios',
        summary: 'Uma mensagem que os sócios veem ao entrar na sua área.',
        recap: '**Avisos aos sócios** › **Nova notificação**, escolha tipo e destinatários e **Guardar**.',
        minutes: 1,
        audience: 'direcao',
        tab: 'notifications',
        related: ['documentos-socios', 'partilhar-redes'],
        keywords: ['avisos', 'notificações', 'mensagem', 'sócios', 'urgente', 'assembleia', 'convocatória'],
        steps: [
            { text: 'Abra **Avisos aos sócios** e carregue em **Nova notificação**.' },
            { text: 'Escreva o **Título** e a **Mensagem**.' },
            { text: 'Escolha o **Tipo**: Informação, Aviso, Urgente ou Sucesso.' },
            { text: 'Escolha os **Destinatários**: Todos, Sócios ou Administração.' },
            { text: 'Carregue em **Guardar**. O aviso aparece em **Notificações**, na área de sócio.', warning: 'Um aviso não envia email. Para assuntos importantes, avise também no grupo de WhatsApp.' },
        ],
    },
    {
        id: 'categorias',
        category: 'socios',
        title: 'Categorias de eventos e notícias',
        summary: 'Nome e cor que agrupam a agenda e as notícias.',
        recap: '**Categorias** › **Nova categoria**, com nome e cor; fica logo disponível nos eventos e notícias.',
        minutes: 1,
        audience: 'direcao',
        tab: 'categories',
        related: ['criar-evento', 'publicar-noticia'],
        keywords: ['categorias', 'cor', 'filtro', 'agrupar', 'tipo de evento'],
        steps: [
            { text: 'Abra **Categorias** e carregue em **Nova categoria**.' },
            { text: 'Dê um **Nome**, como Cultura, Desporto ou Social.' },
            { text: 'Escolha a **Cor da categoria** e carregue em **Guardar**.', why: 'A cor ajuda os visitantes a distinguir os tipos de evento na agenda.' },
        ],
    },
];

export const ACCESS_TUTORIALS: HelpTutorial[] = [
    {
        id: 'dar-acesso',
        category: 'acessos',
        title: 'Dar acesso a um membro da direção ou a um sócio',
        summary: 'A conta fica criada com uma palavra-passe temporária pronta a enviar.',
        recap: '**Acessos** › **Dar acesso**, escolha o tipo e envie a mensagem com **Copiar mensagem**.',
        minutes: 2,
        audience: 'direcao',
        tab: 'access',
        related: ['repor-palavra-passe', 'mudar-tipo-remover', 'socios-quotas'],
        keywords: ['acessos', 'dar acesso', 'nova conta', 'administrador', 'sócio', 'palavra-passe temporária', 'convidar', 'utilizador'],
        media: [
            video('dar-acesso', 'Em Acessos carrega-se em Dar acesso, escreve-se o email e o nome, escolhe-se Administrador ou Sócio e carrega-se em Dar acesso. Aparece o cartão Acesso criado com o email, a palavra-passe temporária e o botão Copiar mensagem.'),
            image('acessos-credenciais', 'Cartão Acesso criado com email, palavra-passe temporária e mensagem pronta a copiar'),
        ],
        steps: [
            { text: 'Abra **Acessos** e carregue em **Dar acesso**.' },
            { text: 'Escreva o **Email** e, se quiser, o **Nome (opcional)**.', why: 'O nome aparece na saudação do painel e no cartão de sócio.' },
            { text: 'Em **Tipo de acesso**, escolha **Administrador** (gere o site) ou **Sócio** (só a área de sócio).' },
            { text: 'Carregue em **Dar acesso**. Aparece a palavra-passe temporária.' },
            { text: 'Carregue em **Copiar mensagem** e envie-a por WhatsApp ou email, em privado.', warning: 'A palavra-passe só é mostrada agora. Nunca a envie para um grupo.' },
            { text: 'Peça à pessoa para mudar a palavra-passe em **Alterar palavra-passe** depois de entrar.' },
        ],
    },
    {
        id: 'repor-palavra-passe',
        category: 'acessos',
        title: 'Alguém se esqueceu da palavra-passe',
        summary: 'Gere uma palavra-passe temporária nova em segundos.',
        recap: '**Acessos** › ícone do olho (**Gerir**) › **Nova palavra-passe**, e envie a mensagem em privado.',
        minutes: 1,
        audience: 'direcao',
        tab: 'access',
        related: ['dar-acesso', 'resolver-problemas'],
        keywords: ['esqueci', 'esqueceu', 'recuperar', 'repor', 'nova palavra-passe', 'reset', 'bloqueado', 'não consegue entrar'],
        steps: [
            { text: 'Abra **Acessos** e encontre a pessoa na lista.' },
            { text: 'Carregue no ícone do olho (**Gerir**) nessa linha.' },
            { text: 'Em **Esqueceu-se da palavra-passe?**, carregue em **Nova palavra-passe**.', why: 'As sessões abertas dessa conta terminam: quem a usava sem autorização perde o acesso.' },
            { text: 'Copie a mensagem e envie-a à pessoa em privado.', tip: 'Esqueceu-se da sua? Peça a outro administrador: ninguém repõe a própria palavra-passe.' },
        ],
    },
    {
        id: 'mudar-tipo-remover',
        category: 'acessos',
        title: 'Mudar o tipo de acesso ou remover uma conta',
        summary: 'Quando alguém entra ou sai da direção.',
        recap: 'Em **Acessos** › **Gerir**, use **Tornar administrador** ou **Retirar administração**; apague só quem saiu.',
        minutes: 1,
        audience: 'direcao',
        tab: 'access',
        related: ['dar-acesso', 'rgpd-basico'],
        keywords: ['tornar administrador', 'retirar administração', 'remover conta', 'apagar conta', 'nova direção', 'mandato'],
        steps: [
            { text: 'Em **Acessos**, carregue no ícone do olho (**Gerir**) da pessoa.' },
            { text: 'Carregue em **Tornar administrador** ou **Retirar administração**.', tip: 'Quem deixa de ser administrador mantém a área de sócio.' },
            { text: 'Para apagar a conta, use o botão de apagar na lista e confirme.', warning: 'Não pode mudar nem apagar a sua própria conta: peça a outro administrador.' },
            { text: 'Em cada mudança de mandato, reveja a lista de administradores.', why: 'Só quem está na direção deve conseguir mudar o site.' },
        ],
    },
];
