import { image, video } from './media';
import type { HelpTutorial } from './types';

export const MEMBER_TUTORIALS: HelpTutorial[] = [
    {
        id: 'socios-quotas',
        category: 'socios',
        title: 'Registar sócios e marcar quotas pagas',
        summary: 'O número de sócio e o ano da quota que cada sócio vê na sua área.',
        minutes: 3,
        audience: 'direcao',
        tab: 'member-quotas',
        featured: true,
        keywords: ['sócios', 'quotas', 'quota paga', 'número de sócio', 'atrasada', 'em dia', 'pagamento', 'cartão de sócio'],
        media: [image('socios-quotas', 'Separador Sócios & Quotas com a lista de sócios, o número e o estado da quota')],
        steps: [
            { text: 'Abra "Sócios & Quotas" e carregue em "Adicionar sócio".' },
            { text: 'Escreva o "Email" com que o sócio entra no site. É o email que liga o registo à conta.', warning: 'Se o email não for exatamente o da conta, o sócio não vê o número nem a quota.' },
            { text: 'Preencha o "Nº Sócio" e, em "Quota paga até", o último ano pago (por exemplo 2026).' },
            { text: 'Use "Notas" para o que for útil à direção (pagou em dinheiro, quota familiar...). O sócio não vê as notas.' },
            { text: 'Carregue em "Guardar". Quando receber um pagamento, edite o sócio e atualize o ano.', tip: 'Os filtros "Em dia", "Atrasada" e "Sem ano" mostram logo quem tem quotas por pagar.' },
        ],
    },
    {
        id: 'documentos-socios',
        category: 'socios',
        title: 'Partilhar documentos com os sócios',
        summary: 'Estatutos, atas e regulamentos na área de sócio.',
        minutes: 2,
        audience: 'direcao',
        tab: 'documents',
        keywords: ['documentos', 'atas', 'estatutos', 'regulamentos', 'relatórios', 'pdf', 'ficheiro'],
        steps: [
            { text: 'Guarde o PDF num serviço com link de partilha (Google Drive, OneDrive) e copie o link.' },
            { text: 'Abra "Documentos" e carregue em "Novo documento".' },
            { text: 'Preencha "Título", escolha a "Categoria" (Atas, Relatórios, Estatutos, Regulamentos ou Outros) e cole o link em "Link do ficheiro".' },
            { text: 'Carregue em "Guardar". O documento aparece aos sócios em "Documentos", na área de sócio.', tip: 'Confirme que o link abre sem pedir autorização: experimente-o numa janela anónima.' },
        ],
    },
    {
        id: 'avisos-socios',
        category: 'socios',
        title: 'Enviar um aviso aos sócios',
        summary: 'Uma mensagem que os sócios veem ao entrar na sua área.',
        minutes: 1,
        audience: 'direcao',
        tab: 'notifications',
        keywords: ['avisos', 'notificações', 'mensagem', 'sócios', 'urgente', 'assembleia', 'convocatória'],
        steps: [
            { text: 'Abra "Avisos aos sócios" e carregue em "Nova notificação".' },
            { text: 'Escreva o "Título" e a "Mensagem".' },
            { text: 'Escolha o "Tipo" (Informação, Aviso, Urgente ou Sucesso) e os "Destinatários" (Todos, Sócios ou Administração).' },
            { text: 'Carregue em "Guardar". O aviso aparece em "Notificações", na área de sócio.', tip: 'Um aviso não envia email: para assuntos importantes, avise também pelo grupo de WhatsApp.' },
        ],
    },
    {
        id: 'categorias',
        category: 'socios',
        title: 'Categorias de eventos e notícias',
        summary: 'Nome e cor que agrupam a agenda e as notícias.',
        minutes: 1,
        audience: 'direcao',
        tab: 'categories',
        keywords: ['categorias', 'cor', 'filtro', 'agrupar', 'tipo de evento'],
        steps: [
            { text: 'Abra "Categorias" e carregue em "Nova categoria".' },
            { text: 'Dê um "Nome" (Cultura, Desporto, Social...) e escolha a "Cor da categoria".' },
            { text: 'Carregue em "Guardar". A categoria passa a estar disponível nos eventos e nas notícias.' },
        ],
    },
];

export const ACCESS_TUTORIALS: HelpTutorial[] = [
    {
        id: 'dar-acesso',
        category: 'acessos',
        title: 'Dar acesso a um membro da direção ou a um sócio',
        summary: 'A conta fica criada com uma palavra-passe temporária pronta a enviar.',
        minutes: 2,
        audience: 'direcao',
        tab: 'access',
        featured: true,
        keywords: ['acessos', 'dar acesso', 'nova conta', 'administrador', 'sócio', 'palavra-passe temporária', 'convidar', 'utilizador'],
        media: [
            video('dar-acesso', 'Em Acessos carrega-se em Dar acesso, escreve-se o email e o nome, escolhe-se Administrador ou Sócio e carrega-se em Dar acesso. Aparece o cartão Acesso criado com o email, a palavra-passe temporária e o botão Copiar mensagem.'),
            image('acessos-credenciais', 'Cartão Acesso criado com email, palavra-passe temporária e mensagem pronta a copiar'),
        ],
        steps: [
            { text: 'Abra "Acessos" e carregue em "Dar acesso".' },
            { text: 'Escreva o "Email" e, se quiser, o "Nome" (aparece na saudação e no cartão de sócio).' },
            { text: 'Em "Tipo de acesso", escolha "Administrador" (gere o site) ou "Sócio" (só a área de sócio).' },
            { text: 'Carregue em "Dar acesso". Aparece a palavra-passe temporária.' },
            { text: 'Carregue em "Copiar mensagem" e envie-a por WhatsApp ou email: leva o endereço do site, o email e a palavra-passe.', warning: 'A palavra-passe só é mostrada agora. Envie-a por um canal privado, nunca num grupo.' },
            { text: 'Peça à pessoa que mude a palavra-passe depois de entrar, em "Alterar palavra-passe".' },
        ],
    },
    {
        id: 'repor-palavra-passe',
        category: 'acessos',
        title: 'Alguém se esqueceu da palavra-passe',
        summary: 'Gere uma palavra-passe temporária nova em segundos.',
        minutes: 1,
        audience: 'direcao',
        tab: 'access',
        keywords: ['esqueci', 'esqueceu', 'recuperar', 'repor', 'nova palavra-passe', 'reset', 'bloqueado'],
        steps: [
            { text: 'Abra "Acessos", encontre a pessoa e carregue em "Gerir".' },
            { text: 'Em "Esqueceu-se da palavra-passe?", carregue em "Nova palavra-passe".' },
            { text: 'Copie a mensagem e envie-a à pessoa por um canal privado.', tip: 'As sessões abertas dessa conta terminam: se alguém estava a usar a conta sem autorização, perde o acesso.' },
        ],
    },
    {
        id: 'mudar-tipo-remover',
        category: 'acessos',
        title: 'Mudar o tipo de acesso ou remover uma conta',
        summary: 'Quando alguém entra ou sai da direção.',
        minutes: 1,
        audience: 'direcao',
        tab: 'access',
        keywords: ['tornar administrador', 'retirar administração', 'remover conta', 'apagar conta', 'nova direção', 'mandato'],
        steps: [
            { text: 'Em "Acessos", carregue em "Gerir" na pessoa.' },
            { text: 'Carregue em "Tornar administrador" ou "Retirar administração". Quem deixa de ser administrador mantém a área de sócio.' },
            { text: 'Para apagar a conta, use o botão de apagar na lista e confirme.', warning: 'Não pode remover nem mudar a sua própria conta: peça a outro administrador.' },
            { text: 'Em cada mudança de mandato, reveja a lista: só quem está na direção deve ser administrador.' },
        ],
    },
];
