import { image, video } from './media';
import type { HelpTutorial } from './types';

export const NEWS_TUTORIALS: HelpTutorial[] = [
    {
        id: 'publicar-noticia',
        category: 'noticias',
        title: 'Publicar uma notícia',
        summary: 'Texto, imagem de capa e publicação, com ajuda da IA se quiser.',
        recap: '**Notícias** › **Nova notícia**, escreva, junte a capa, marque **Publicada** e carregue em **Guardar**.',
        minutes: 3,
        audience: 'direcao',
        tab: 'news',
        related: ['criar-com-ia', 'imagens-leves', 'partilhar-redes'],
        keywords: ['notícia', 'blog', 'nova notícia', 'publicar', 'capa', 'imagem de capa', 'autor', 'rascunho'],
        steps: [
            { text: 'Abra **Notícias** e carregue em **Nova notícia**.' },
            { text: 'Preencha **Título**, **Categoria** e **Data**.' },
            { text: 'Escreva o texto em **Notícia**.', tip: 'Use negrito, títulos e listas para o organizar. **Melhorar** revê o texto com IA.' },
            { text: 'Em **Imagem de capa**, carregue uma fotografia do momento.', why: 'Uma fotografia real do evento chama mais a atenção do que uma imagem genérica.' },
            { text: 'Marque **Publicada (visível no site)** quando estiver pronta.', tip: 'Desmarcada, a notícia fica guardada como rascunho.' },
            { text: 'Opcional: em **Mais opções: autor e palavras-chave**, indique quem escreveu.' },
            { text: 'Carregue em **Guardar** e partilhe a notícia a partir do site.' },
        ],
    },
];

export const AI_TUTORIALS: HelpTutorial[] = [
    {
        id: 'criar-com-ia',
        category: 'ia',
        title: 'Criar um evento ou uma notícia com IA',
        summary: 'Escreva duas linhas; a IA preenche o formulário e pode criar o cartaz.',
        recap: '**Criar com IA**, descreva o essencial, carregue em **Criar rascunho**, reveja e **Guardar**.',
        minutes: 3,
        audience: 'direcao',
        tab: 'events',
        relatedTabs: ['news'],
        featured: true,
        related: ['ia-dicas-descricao', 'ia-cartaz-referencia', 'ia-custos-orcamento'],
        keywords: ['ia', 'inteligência artificial', 'criar com ia', 'estúdio', 'rascunho', 'cartaz', 'automático'],
        media: [
            video('criar-evento-ia', 'Em Eventos carrega-se em Criar com IA, escreve-se uma frase com o quê, quando, onde e preço, e carrega-se em Criar rascunho. O formulário do evento abre preenchido para rever antes de guardar.'),
            image('estudio-ia', 'Janela Criar evento com IA com a descrição, os exemplos, a imagem de referência e as opções do cartaz'),
        ],
        steps: [
            { text: 'Em **Eventos** ou **Notícias**, carregue em **Criar com IA**.' },
            { text: 'Em **O que quer anunciar?**, escreva o quê, quando, onde, o preço e como se inscrever.', tip: 'Os exemplos por baixo do campo mostram o tom certo.' },
            { text: 'Deixe marcado **Gerar cartaz** (ou **Gerar imagem de capa**) se quiser imagem.', tip: 'Nos eventos, **Cartaz com texto** decide se o cartaz leva letras.' },
            { text: 'Veja o **Custo estimado**, por baixo das opções.', why: 'Sabe quanto vai custar antes de gerar. Sem imagem, o custo é quase zero.' },
            { text: 'Carregue em **Criar rascunho** e espere.', tip: 'Sem cartaz demora segundos; com cartaz, de 10 segundos a 2 minutos, conforme o motor.' },
            { text: 'O formulário abre preenchido. Reveja datas, preços e nomes.', warning: 'A IA pode enganar-se numa data ou num preço. Confirme sempre antes de publicar.' },
            { text: 'Carregue em **Guardar**. A mensagem no fundo diz quanto custou este rascunho.' },
        ],
    },
    {
        id: 'ia-dicas-descricao',
        category: 'ia',
        title: 'Dicas para uma boa descrição',
        summary: 'O que escrever para a IA acertar à primeira.',
        recap: 'Diga o quê, quando, onde e quanto custa, com o dia exato; junte o que torna o evento especial.',
        minutes: 2,
        audience: 'direcao',
        tab: 'events',
        relatedTabs: ['news'],
        related: ['criar-com-ia', 'ia-cartaz-referencia'],
        keywords: ['dicas', 'descrição', 'brief', 'prompt', 'texto', 'escrever'],
        steps: [
            { text: 'Diga o quê, quando, onde e quanto custa.', tip: 'Exemplo: "Magusto a 11 de novembro às 16h no largo da sede, entrada livre".' },
            { text: 'Junte o que torna o evento especial: música, comida, prémios, para quem é.' },
            { text: 'Numa notícia, conte o que aconteceu e com quem.', tip: 'Exemplo: "14 duplas em prova, venceu a dupla Silva e Costa".' },
            { text: 'Escreva o dia exato, como "sábado, 12 de abril", e não só "sábado".', why: 'A IA sabe a data de hoje, mas um dia exato evita enganos.' },
            { text: 'Não ficou como queria? Corrija no formulário, ou feche e reescreva a frase.' },
        ],
    },
    {
        id: 'ia-cartaz-referencia',
        category: 'ia',
        title: 'Usar o cartaz do ano passado como referência',
        summary: 'A IA lê o cartaz antigo e atualiza edição, datas e preços com a sua descrição.',
        recap: 'Junte o cartaz antigo em **Imagem de referência (opcional)** e escreva só o que muda.',
        minutes: 2,
        audience: 'direcao',
        tab: 'events',
        related: ['criar-com-ia', 'ia-dicas-descricao'],
        keywords: ['referência', 'cartaz antigo', 'ano passado', 'imagem de referência', 'edição', 'reaproveitar'],
        steps: [
            { text: 'Em **Criar com IA**, arraste o cartaz antigo para **Imagem de referência (opcional)**.', tip: 'Também pode tocar na zona e escolher o ficheiro (JPG, PNG ou WebP).' },
            { text: 'Espere até aparecer **Referência pronta**.' },
            { text: 'Na descrição, escreva só o que muda: "6.ª edição, 18 de outubro, inscrições a 10 €".' },
            { text: 'Carregue em **Criar rascunho**.', why: 'A IA aproveita o que estava no cartaz e atualiza o resto.' },
        ],
    },
    {
        id: 'ia-motor-custos',
        category: 'ia',
        title: 'Escolher o motor de imagem',
        summary: 'NanoBanana para o dia a dia, GPT Image quando o cartaz tem de ser perfeito.',
        recap: '**NanoBanana** é o motor por omissão, rápido e barato; **GPT Image** dá a qualidade máxima.',
        minutes: 2,
        audience: 'direcao',
        tab: 'ai',
        relatedTabs: ['events', 'news'],
        related: ['ia-custos-orcamento', 'criar-com-ia'],
        keywords: ['motor de imagem', 'gpt image', 'nanobanana', 'gemini', 'openrouter', 'qualidade máxima', 'cartaz', 'recomendado'],
        steps: [
            { text: 'Abra **Assistente virtual** e desça até **Motor de imagem**.' },
            { text: 'Para o dia a dia, escolha **NanoBanana (Gemini) · recomendado**.', why: 'Cerca de 10 segundos e 0,07 $ por cartaz, com bom texto em cartazes simples.' },
            { text: 'Para um cartaz especial, escolha **GPT Image (OpenRouter) · qualidade máxima**.', why: 'Texto mais rigoroso, ao nível de uma gráfica: cerca de 2 minutos e 0,23 $ por cartaz.' },
            { text: 'Carregue em **Guardar alterações**.', tip: 'Se o motor escolhido falhar, o outro é tentado automaticamente.' },
            { text: 'Para um só cartaz, troque o **Motor de imagem** dentro de **Criar com IA**.', tip: 'Esse campo só aparece quando o OpenRouter está configurado.' },
        ],
    },
    {
        id: 'ia-custos-orcamento',
        category: 'ia',
        title: 'Ver quanto custa a IA e definir orçamento',
        summary: 'O custo antes e depois de gerar, o gasto do mês e um aviso quando passar do orçamento.',
        recap: 'O gasto está em **Início** › **IA este mês** e em **Utilização e custos**; o orçamento é opcional.',
        minutes: 2,
        audience: 'direcao',
        tab: 'ai',
        relatedTabs: ['dashboard', 'events', 'news'],
        related: ['ia-motor-custos', 'criar-com-ia', 'resolver-problemas'],
        keywords: ['custo', 'custos', 'preço', 'quanto custa', 'gasto', 'orçamento', 'orçamento mensal', 'dólares', 'saldo', 'utilização'],
        steps: [
            { text: 'Em **Início**, veja o cartão **IA este mês**: gasto e número de pedidos.' },
            { text: 'Para o detalhe, abra **Assistente virtual**. **Utilização e custos** é a primeira secção.' },
            { text: 'Escolha o período: **7 dias**, **30 dias** ou **Este mês**.', tip: 'Os valores estão em dólares, a moeda em que os serviços de IA cobram.' },
            { text: 'Veja **Custo total**, **Por função** e **Últimos pedidos** para saber quem gastou e em quê.' },
            { text: 'Opcional: escreva um valor em **Orçamento mensal (USD)**. Vazio quer dizer sem orçamento.' },
            { text: 'Carregue em **Guardar alterações**.', why: 'Ao passar o orçamento, o estúdio avisa antes de gerar, mas não bloqueia.' },
            { text: 'Ao gerar, confira o **Custo estimado**; no fim, a mensagem diz quanto custou.' },
        ],
    },
];
