import { image } from './media';
import type { HelpTutorial } from './types';

export const PEOPLE_TUTORIALS: HelpTutorial[] = [
    {
        id: 'equipa-corpos-sociais',
        category: 'equipa',
        title: 'Atualizar a equipa e os corpos sociais',
        summary: 'Quem aparece na página Equipa, com cargo, fotografia e ordem.',
        recap: '**Membros** › **Novo membro**, com nome, cargo, grupo e ordem; edite os cargos quando muda o mandato.',
        minutes: 2,
        audience: 'direcao',
        tab: 'members',
        related: ['historia-linha-tempo', 'mudar-tipo-remover'],
        keywords: ['equipa', 'membros', 'direção', 'assembleia geral', 'conselho fiscal', 'fundador', 'cargo', 'fotografia', 'mandato'],
        steps: [
            { text: 'Abra **Membros** e carregue em **Novo membro**.' },
            { text: 'Preencha **Nome** e **Cargo**.' },
            { text: 'Em **Grupo**, escolha Direção, Assembleia Geral, Conselho Fiscal ou Sócio Fundador.', tip: 'Os sócios fundadores aparecem na página História.' },
            { text: 'Junte uma fotografia e indique a **Ordem**: números mais baixos aparecem primeiro.' },
            { text: 'Carregue em **Guardar**.', tip: 'Mudou o mandato? Edite os cargos e atualize o **Mandato Atual** em **Definições** › **Contacto & Localização**.' },
        ],
    },
    {
        id: 'parceiros-niveis',
        category: 'equipa',
        title: 'Parceiros e níveis de parceria',
        summary: 'Logótipos na faixa da página inicial e os níveis propostos a novos apoios.',
        recap: '**Parceiros** guarda os logótipos; **Níveis de Parceria** define o que cada apoio inclui.',
        minutes: 3,
        audience: 'direcao',
        tab: 'sponsors',
        relatedTabs: ['tiers'],
        related: ['mensagens-recebidas', 'imagens-leves'],
        keywords: ['parceiros', 'patrocinadores', 'apoios', 'logótipo', 'níveis de parceria', 'benefícios', 'patrocínio'],
        steps: [
            { text: 'Em **Parceiros**, carregue em **Novo parceiro**.' },
            { text: 'Preencha **Nome** e **Website** e junte o logótipo.', tip: 'Prefira logótipos com fundo transparente (PNG ou SVG).' },
            { text: 'Escolha o **Nível** e deixe marcado **Ativo (visível no portal)**.', tip: 'Desmarque para esconder o parceiro sem o apagar.' },
            { text: 'Para criar níveis, abra **Níveis de Parceria** e carregue em **Novo nível**.' },
            { text: 'Indique nome, preço e benefícios, um por linha, e carregue em **Guardar**.', why: 'Os níveis aparecem no formulário de parcerias do site; os pedidos chegam a **Mensagens recebidas**.' },
        ],
    },
    {
        id: 'mensagens-recebidas',
        category: 'equipa',
        title: 'Responder a mensagens e pedidos de parceria',
        summary: 'Tudo o que chega pelos formulários do site, num só sítio.',
        recap: 'Em **Mensagens recebidas**, responda por email e marque **Marcar respondido** ou **Arquivar**.',
        minutes: 2,
        audience: 'direcao',
        tab: 'leads',
        related: ['parceiros-niveis', 'rgpd-basico'],
        keywords: ['mensagens', 'contactos', 'pedidos de parceria', 'responder', 'arquivar', 'email', 'formulário de contacto'],
        steps: [
            { text: 'Abra **Mensagens recebidas**. Em **Contactos** estão as mensagens do formulário do site.' },
            { text: 'Carregue no email da pessoa para lhe responder no seu programa de email.' },
            { text: 'Depois de responder, carregue em **Marcar respondido**.' },
            { text: 'Use **Arquivar** para tirar da frente o que já está tratado.' },
            { text: 'Em **Pedidos de Parceria**, marque **Marcar contactado** e, no fim, **Confirmar** ou **Rejeitar**.', why: 'Assim toda a direção sabe em que ponto está cada proposta.' },
        ],
    },
    {
        id: 'historia-linha-tempo',
        category: 'equipa',
        title: 'Contar a história da associação',
        summary: 'Os marcos da linha do tempo da página História.',
        recap: '**História** › **Novo marco**, com ano, título e descrição; a ordem acerta-se em **Ordem na Timeline**.',
        minutes: 2,
        audience: 'direcao',
        tab: 'historia',
        related: ['identidade-textos', 'equipa-corpos-sociais'],
        keywords: ['história', 'linha do tempo', 'timeline', 'marco', 'ano', 'fundação'],
        steps: [
            { text: 'Abra **História** e carregue em **Novo marco**.' },
            { text: 'Indique o **Ano**, o **Título** e uma **Descrição** curta.', tip: 'Junte uma fotografia antiga, se tiver: dá vida à página.' },
            { text: 'Acerte a sequência em **Ordem na Timeline** e carregue em **Guardar**.', tip: 'A introdução e a citação da página editam-se em **Definições** › **Identidade & Textos**.' },
        ],
    },
];

export const GALLERY_TUTORIALS: HelpTutorial[] = [
    {
        id: 'galeria-album',
        category: 'galeria',
        title: 'Criar um álbum e carregar fotografias',
        summary: 'Várias fotos de uma vez, reduzidas automaticamente para o site.',
        recap: '**Galeria** › **Novo álbum**, escolha o álbum e arraste as fotografias, muitas de uma vez.',
        minutes: 3,
        audience: 'direcao',
        tab: 'gallery',
        related: ['galeria-legendas-ordem', 'imagens-leves'],
        keywords: ['galeria', 'álbum', 'fotos', 'fotografias', 'carregar', 'upload', 'várias'],
        media: [image('galeria', 'Gestor de galeria com a lista de álbuns, a zona para arrastar fotos e a grelha de fotografias')],
        steps: [
            { text: 'Abra **Galeria** e carregue em **Novo álbum**.' },
            { text: 'Escreva o **Título do Álbum** e a **Data** e carregue em **Guardar**.' },
            { text: 'Escolha o álbum na lista.' },
            { text: 'Arraste as fotografias para a zona **Arrasta fotos para aqui ou clica para escolher**.', why: 'As fotos são reduzidas antes de subir: pode usar as do telemóvel tal como estão.' },
            { text: 'Acompanhe o progresso; no fim aparece quantas fotografias foram adicionadas.' },
        ],
    },
    {
        id: 'galeria-legendas-ordem',
        category: 'galeria',
        title: 'Legendas, ordem e capa do álbum',
        summary: 'Arrumar o álbum para que conte a história do evento.',
        recap: 'Escreva as legendas, mude a ordem com as setas e escolha a capa na estrela.',
        minutes: 2,
        audience: 'direcao',
        tab: 'gallery',
        related: ['galeria-album', 'imagens-leves'],
        keywords: ['legenda', 'ordem', 'capa', 'estrela', 'apagar fotos', 'organizar', 'selecionar'],
        steps: [
            { text: 'Escreva a legenda por baixo de cada foto, em **Legenda (opcional)**.', tip: 'A legenda fica guardada quando sai do campo.' },
            { text: 'Passe o rato sobre uma foto e use as setas para a mudar de lugar.' },
            { text: 'Carregue na estrela da foto que deve representar o álbum.', why: 'A capa é a foto que aparece na lista de álbuns da galeria.' },
            { text: 'Para apagar várias, marque a caixa no canto de cada uma.', tip: '**Selecionar todas** marca o álbum inteiro de uma vez.' },
            { text: 'Carregue em **Apagar** e confirme. O botão mostra quantas fotos vão sair.', warning: 'As fotos apagadas não se recuperam.' },
        ],
    },
];
