import { image } from './media';
import type { HelpTutorial } from './types';

export const PUBLIC_TUTORIALS: HelpTutorial[] = [
    {
        id: 'inscrever-evento',
        category: 'inscricoes-publico',
        title: 'Inscrever-se num evento',
        summary: 'Sem conta, só com nome e email. Demora um minuto.',
        recap: 'Abra o evento, carregue em **Inscrever-me**, escreva o nome e o email e carregue em **Enviar inscrição**.',
        minutes: 1,
        audience: 'socio',
        featured: true,
        related: ['cancelar-inscricao', 'inscrever-com-conta'],
        keywords: ['inscrição', 'inscrever', 'evento', 'sem conta', 'bilhete', 'participar', 'torneio', 'esgotado'],
        media: [image('evento-inscricao', 'Formulário de inscrição de um evento com nome, email, telemóvel e perguntas do evento')],
        steps: [
            { text: 'Abra **Eventos** no menu, ou o link do evento que recebeu.' },
            { text: 'No evento, carregue em **Ver e inscrever-me**.' },
            { text: 'Carregue em **Inscrever-me (grátis)**, ou em **Inscrever-me** com o preço ao lado.', tip: 'Se aparecer **Esgotado**, já não há lugares.' },
            { text: 'Escreva o nome e o email. O telemóvel é opcional.', tip: 'Alguns eventos pedem mais, como o nome da equipa.' },
            { text: 'Carregue em **Enviar inscrição**. Aparece **Inscrição recebida**.', tip: '**Guardar no calendário** lembra-o do dia; **Convide alguém** partilha o evento.' },
            { text: 'Aguarde a confirmação da organização, pelo email que indicou.' },
        ],
    },
    {
        id: 'inscrever-com-conta',
        category: 'inscricoes-publico',
        title: 'Eventos só para sócios',
        summary: 'Alguns eventos pedem que entre com a sua conta antes de se inscrever.',
        recap: 'Carregue em **Iniciar sessão para inscrever**, entre, volte ao evento e inscreva-se.',
        minutes: 1,
        audience: 'socio',
        related: ['inscrever-evento', 'area-socio'],
        keywords: ['sócios', 'conta', 'iniciar sessão', 'entrar', 'evento reservado', 'só sócios'],
        steps: [
            { text: 'No evento, carregue em **Iniciar sessão para inscrever**.' },
            { text: 'Escreva o seu **Email** e a **Palavra-passe** e carregue em **Entrar**.', tip: 'Ainda não tem conta? Peça-a à direção da {siteName}.' },
            { text: 'Abre-se a sua área de sócio. Volte a **Eventos** e abra o mesmo evento.' },
            { text: 'Carregue em **Inscrever-me**. O email da sua conta já vem preenchido.' },
        ],
    },
    {
        id: 'cancelar-inscricao',
        category: 'inscricoes-publico',
        title: 'Cancelar ou alterar uma inscrição',
        summary: 'Não pode ir? Avise a organização para libertar o lugar.',
        recap: 'Contacte a direção com o nome do evento e o nome com que se inscreveu.',
        minutes: 1,
        audience: 'socio',
        related: ['inscrever-evento', 'contactar-direcao'],
        keywords: ['cancelar', 'desistir', 'alterar', 'mudar inscrição', 'não posso ir', 'pagamento'],
        steps: [
            { text: 'Carregue em **Contacte-nos**, no fim de qualquer página.' },
            { text: 'Escreva o nome do evento e o nome com que se inscreveu.' },
            { text: 'Diga se quer cancelar ou o que quer alterar e carregue em **Enviar pedido**.', why: 'Ao cancelar, o lugar fica livre para outra pessoa.' },
            { text: 'A direção trata do pedido e responde para o seu email.', tip: 'Nos eventos pagos, o reembolso combina-se diretamente com a organização.' },
        ],
    },
    {
        id: 'area-socio',
        category: 'area-socio',
        title: 'A sua área de sócio',
        summary: 'Cartão digital, estado da quota, documentos e avisos da direção.',
        recap: 'Entre em **Sócio** para ver o cartão, a quota, os documentos e os avisos.',
        minutes: 2,
        audience: 'socio',
        featured: true,
        related: ['pagar-quota', 'alterar-palavra-passe-socio'],
        keywords: ['área de sócio', 'cartão', 'cartão de sócio', 'número de sócio', 'documentos', 'notificações', 'avisos', 'entrar'],
        media: [image('area-socio', 'Área de sócio com o cartão digital e os cartões de quotas, notificações e documentos')],
        steps: [
            { text: 'Carregue em **Sócio**, no topo do site.', tip: 'No telemóvel, abra o menu e escolha **Área de Sócio**.' },
            { text: 'Escreva o seu email e a palavra-passe e carregue em **Entrar**.' },
            { text: 'Em **Dashboard** vê o cartão de sócio com o número. Toque no cartão para o virar.' },
            { text: 'O cartão **Quotas** mostra se a quota está em dia e até quando.' },
            { text: 'Em **Documentos** estão os estatutos, atas e regulamentos da {siteName}.' },
            { text: 'Em **Notificações** estão os avisos da direção.', tip: 'Não vê o seu número de sócio? Peça à direção para confirmar o email registado.' },
        ],
    },
    {
        id: 'pagar-quota',
        category: 'area-socio',
        title: 'Pagar a quota',
        summary: 'MB WAY, transferência ou Multibanco, conforme o que a direção disponibiliza.',
        recap: 'Na área de sócio, carregue em **Como pagar**, copie os dados e pague na app do banco.',
        minutes: 1,
        audience: 'socio',
        featured: true,
        related: ['area-socio', 'contactar-direcao'],
        keywords: ['quota', 'pagar', 'pagamento', 'mb way', 'iban', 'transferência', 'multibanco', 'referência'],
        steps: [
            { text: 'Na área de sócio, no cartão **Quotas**, carregue em **Como pagar**.' },
            { text: 'Escolha a forma de pagamento: MB WAY, transferência ou Multibanco.' },
            { text: 'Toque no botão de copiar ao lado do número, IBAN ou referência.' },
            { text: 'Abra a app do banco, cole os dados e pague.' },
            { text: 'A direção confirma o pagamento e atualiza a sua quota.', tip: 'Não aparecem formas de pagamento? Carregue em **Contactar a Direção**.' },
        ],
    },
    {
        id: 'alterar-palavra-passe-socio',
        category: 'conta',
        title: 'Alterar a palavra-passe',
        summary: 'Troque a palavra-passe temporária por uma só sua.',
        recap: 'Na área de sócio, **Alterar palavra-passe**: a atual, a nova duas vezes e **Guardar**.',
        minutes: 1,
        audience: 'socio',
        related: ['esqueci-palavra-passe', 'area-socio'],
        keywords: ['palavra-passe', 'password', 'senha', 'alterar', 'mudar', 'temporária'],
        steps: [
            { text: 'Entre na área de sócio e carregue em **Alterar palavra-passe**.' },
            { text: 'Escreva a palavra-passe atual. Se é a primeira vez, é a temporária.' },
            { text: 'Escreva a nova duas vezes.', tip: 'Pelo menos 10 caracteres, com maiúsculas, minúsculas e um número.' },
            { text: 'Carregue em **Guardar**.', why: 'As outras sessões abertas com a sua conta terminam, por segurança.' },
        ],
    },
    {
        id: 'esqueci-palavra-passe',
        category: 'conta',
        title: 'Esqueci-me da palavra-passe',
        summary: 'A direção gera-lhe uma palavra-passe temporária nova.',
        recap: 'Peça à direção uma palavra-passe nova e mude-a logo depois de entrar.',
        minutes: 1,
        audience: 'socio',
        featured: true,
        related: ['alterar-palavra-passe-socio', 'algo-nao-funciona'],
        keywords: ['esqueci', 'esqueceu', 'recuperar', 'perdi', 'não consigo entrar', 'repor', 'nova palavra-passe'],
        steps: [
            { text: 'Carregue em **Contacte-nos**, no fim da página, e indique o email da sua conta.' },
            { text: 'Receberá uma palavra-passe temporária nova, por mensagem privada.' },
            { text: 'Entre com ela e mude-a logo em **Alterar palavra-passe**.', warning: 'A direção nunca lhe pede a palavra-passe. Não a partilhe com ninguém.' },
        ],
    },
    {
        id: 'contactar-direcao',
        category: 'conta',
        title: 'Falar com a direção',
        summary: 'Formulário de contacto, email, telefone e morada.',
        recap: 'Carregue em **Contacte-nos**, no fim de qualquer página, ou use os contactos do rodapé.',
        minutes: 1,
        audience: 'socio',
        related: ['cancelar-inscricao', 'algo-nao-funciona'],
        keywords: ['contacto', 'contactos', 'email', 'telefone', 'morada', 'mensagem', 'falar', 'ajuda', 'direção'],
        steps: [
            { text: 'No fim de qualquer página, carregue em **Contacte-nos**.' },
            { text: 'Escreva a sua mensagem e carregue em **Enviar pedido**.' },
            { text: 'A resposta chega ao email que indicar.', tip: 'Prefere telefonar? O telefone e a morada da {siteName} estão em **Contactos**, no rodapé.' },
        ],
    },
];
