import { image } from './media';
import type { HelpTutorial } from './types';

export const PUBLIC_TUTORIALS: HelpTutorial[] = [
    {
        id: 'inscrever-evento',
        category: 'inscricoes-publico',
        title: 'Inscrever-se num evento',
        summary: 'Sem conta, só com nome e email. Demora um minuto.',
        minutes: 1,
        audience: 'socio',
        featured: true,
        keywords: ['inscrição', 'inscrever', 'evento', 'sem conta', 'bilhete', 'participar', 'torneio'],
        media: [image('evento-inscricao', 'Formulário de inscrição de um evento com nome, email, telemóvel e perguntas do evento')],
        steps: [
            { text: 'Abra "Eventos" no menu, ou o link do evento que recebeu no WhatsApp.' },
            { text: 'Carregue no evento e depois em "Inscrever-me (grátis)" ou "Inscrever-me", com o preço.' },
            { text: 'Preencha o nome, o email e, se quiser, o telemóvel. Alguns eventos pedem mais informação, como o nome da equipa.' },
            { text: 'Carregue em "Enviar inscrição". Aparece "Inscrição recebida".', tip: 'Use "Guardar no calendário" para não se esquecer, e "Convide alguém" para partilhar com amigos.' },
            { text: 'A organização confirma a inscrição e, se for preciso, contacta-o pelo email que indicou.' },
        ],
    },
    {
        id: 'inscrever-com-conta',
        category: 'inscricoes-publico',
        title: 'Eventos só para sócios',
        summary: 'Alguns eventos pedem que entre com a sua conta antes de se inscrever.',
        minutes: 1,
        audience: 'socio',
        keywords: ['sócios', 'conta', 'iniciar sessão', 'entrar', 'evento reservado'],
        steps: [
            { text: 'Se o evento mostrar "Iniciar sessão para inscrever", carregue nesse botão.' },
            { text: 'Entre com o seu email e palavra-passe de sócio.' },
            { text: 'Volte ao evento e carregue em "Inscrever-me". O email da sua conta já vem preenchido.' },
            { text: 'Ainda não tem conta? Peça-a à direção da {siteName}.' },
        ],
    },
    {
        id: 'cancelar-inscricao',
        category: 'inscricoes-publico',
        title: 'Cancelar ou alterar uma inscrição',
        summary: 'Não pode ir? Avise a organização para libertar o lugar.',
        minutes: 1,
        audience: 'socio',
        keywords: ['cancelar', 'desistir', 'alterar', 'mudar inscrição', 'não posso ir', 'pagamento'],
        steps: [
            { text: 'Contacte a direção pelo telefone ou email que aparecem no fim do site e na confirmação da inscrição.' },
            { text: 'Diga o nome do evento e o nome com que se inscreveu.' },
            { text: 'A direção cancela ou corrige a inscrição; o lugar fica livre para outra pessoa.', tip: 'Nos eventos pagos, o pagamento combina-se diretamente com a organização.' },
        ],
    },
    {
        id: 'area-socio',
        category: 'area-socio',
        title: 'A sua área de sócio',
        summary: 'Cartão digital, estado da quota, documentos e avisos da direção.',
        minutes: 2,
        audience: 'socio',
        featured: true,
        keywords: ['área de sócio', 'cartão', 'cartão de sócio', 'número de sócio', 'documentos', 'notificações', 'avisos', 'entrar'],
        media: [image('area-socio', 'Área de sócio com o cartão digital e os cartões de quotas, notificações e documentos')],
        steps: [
            { text: 'Carregue em "Sócio" no topo do site (no telemóvel, "Área de Sócio" no menu) e entre com o seu email e palavra-passe.' },
            { text: 'Em "Dashboard" vê o seu cartão de sócio com o número. Carregue no cartão para o virar.' },
            { text: 'O cartão "Quotas" mostra se a quota está em dia e até quando.' },
            { text: 'Em "Documentos" estão os estatutos, atas e regulamentos da {siteName}.' },
            { text: 'Em "Notificações" estão os avisos da direção.', tip: 'Não vê o seu número de sócio? Peça à direção para confirmar o email registado.' },
        ],
    },
    {
        id: 'pagar-quota',
        category: 'area-socio',
        title: 'Pagar a quota',
        summary: 'MB WAY, transferência ou Multibanco, conforme o que a direção disponibiliza.',
        minutes: 1,
        audience: 'socio',
        keywords: ['quota', 'pagar', 'pagamento', 'mb way', 'iban', 'transferência', 'multibanco', 'referência'],
        steps: [
            { text: 'Na área de sócio, carregue no cartão "Quotas" ("Como pagar").' },
            { text: 'Escolha a forma de pagamento e use o botão de copiar para levar o número, IBAN ou referência para a app do banco.' },
            { text: 'Depois do pagamento, a direção confirma e atualiza o estado da sua quota.', tip: 'Se não houver formas de pagamento indicadas, carregue em "Contactar a Direção".' },
        ],
    },
    {
        id: 'alterar-palavra-passe-socio',
        category: 'conta',
        title: 'Alterar a palavra-passe',
        summary: 'Troque a palavra-passe temporária por uma só sua.',
        minutes: 1,
        audience: 'socio',
        keywords: ['palavra-passe', 'password', 'senha', 'alterar', 'mudar', 'temporária'],
        steps: [
            { text: 'Entre na área de sócio e carregue em "Alterar palavra-passe".' },
            { text: 'Escreva a palavra-passe atual (a temporária, se for a primeira vez).' },
            { text: 'Escreva a nova duas vezes: pelo menos 10 caracteres, com maiúsculas, minúsculas e um número.' },
            { text: 'Carregue em "Guardar".' },
        ],
    },
    {
        id: 'esqueci-palavra-passe',
        category: 'conta',
        title: 'Esqueci-me da palavra-passe',
        summary: 'A direção gera-lhe uma palavra-passe temporária nova.',
        minutes: 1,
        audience: 'socio',
        keywords: ['esqueci', 'esqueceu', 'recuperar', 'perdi', 'não consigo entrar', 'repor', 'nova palavra-passe'],
        steps: [
            { text: 'Contacte a direção da {siteName} pelo email ou telefone do fim do site e diga o email da sua conta.' },
            { text: 'Recebe uma palavra-passe temporária nova por mensagem privada.' },
            { text: 'Entre com ela e mude-a logo em "Alterar palavra-passe".', warning: 'A direção nunca lhe pede a palavra-passe. Não a partilhe com ninguém.' },
        ],
    },
    {
        id: 'contactar-direcao',
        category: 'conta',
        title: 'Falar com a direção',
        summary: 'Formulário de contacto, email, telefone e morada.',
        minutes: 1,
        audience: 'socio',
        keywords: ['contacto', 'contactos', 'email', 'telefone', 'morada', 'mensagem', 'falar', 'ajuda'],
        steps: [
            { text: 'No fim de qualquer página, carregue em "Contacte-nos" e escreva a sua mensagem.' },
            { text: 'Também encontra aí o email, o telefone e a morada da {siteName}.' },
            { text: 'A resposta chega ao email que indicar.' },
        ],
    },
];
