import { image, video } from './media';
import type { HelpTutorial } from './types';

export const SETTINGS_TUTORIALS: HelpTutorial[] = [
    {
        id: 'identidade-textos',
        category: 'marca',
        title: 'Nome, textos e fotografia da página inicial',
        summary: 'A identidade da {siteName} que aparece em todo o site.',
        recap: 'Em **Definições**, preencha **Geral**, **Identidade & Textos** e **Página Sobre** e carregue em **Guardar alterações**.',
        minutes: 3,
        audience: 'direcao',
        tab: 'settings',
        related: ['mudar-marca', 'contactos-pagamentos', 'historia-linha-tempo'],
        keywords: ['definições', 'nome', 'identidade', 'textos', 'hero', 'fotografia de fundo', 'sede', 'localidade', 'ano de fundação', 'logótipo'],
        steps: [
            { text: 'Abra **Definições**. Em **Geral** ficam o **Nome do Site**, o email e o **URL do logótipo**.' },
            { text: 'Em **Identidade & Textos**, carregue a **Fotografia de fundo da página inicial**.' },
            { text: 'Ainda aí, preencha nome completo, localidade, ano de fundação, tagline e subtítulo.' },
            { text: 'Preencha também a sede e os textos da página História.', why: 'Um campo vazio esconde a secção respetiva no site, em vez de mostrar um espaço em branco.' },
            { text: 'Em **Página Sobre**, escreva a missão e os pilares da associação.' },
            { text: 'Carregue em **Guardar alterações**, no fundo da página.', warning: 'Nada muda no site enquanto não guardar.' },
        ],
    },
    {
        id: 'mudar-marca',
        category: 'marca',
        title: 'Mudar a cor e a letra do site',
        summary: 'Uma cor e duas letras; o contraste fica garantido automaticamente.',
        recap: '**Definições** › **Marca**: escolha a cor e as letras, veja a pré-visualização e **Guardar alterações**.',
        minutes: 2,
        audience: 'direcao',
        tab: 'settings',
        related: ['identidade-textos', 'imagens-leves'],
        keywords: ['marca', 'cor', 'cor da marca', 'letra', 'fonte', 'tipografia', 'guia de marca', 'media kit', 'contraste', 'logótipo'],
        media: [
            video('mudar-marca', 'Em Definições, na secção Marca, escolhe-se uma das cores sugeridas e depois a letra dos títulos. A pré-visualização ao lado e os rácios de contraste atualizam-se de imediato.'),
            image('marca', 'Secção Marca com cor, cores sugeridas, contraste, letras e pré-visualização'),
        ],
        steps: [
            { text: 'Abra **Definições** e desça até **Marca**.' },
            { text: 'Em **Cor da marca**, escolha uma das cores sugeridas ou escreva o código do logótipo.', tip: 'O código tem o formato #rrggbb; quem fez o logótipo sabe dizê-lo.' },
            { text: 'Veja o quadro **Contraste**.', why: 'Cores muito claras são escurecidas nos botões e links, para continuarem fáceis de ler.' },
            { text: 'Escolha a **Letra dos títulos** e a **Letra do texto**.' },
            { text: 'Confira o resultado na **Pré-visualização**.' },
            { text: 'Tem um guia de marca? Cole o link em **Guia de marca / media kit (link)**.', tip: 'Aparece **Marca e imprensa** no rodapé do site.' },
            { text: 'Carregue em **Guardar alterações**.', tip: 'Não vê a mudança no site? Recarregue a página.' },
        ],
    },
    {
        id: 'contactos-pagamentos',
        category: 'marca',
        title: 'Contactos, quotas e dados de pagamento',
        summary: 'Telefone, morada, mapa, redes sociais e as formas de pagar a quota.',
        recap: 'Em **Definições**, preencha **Contacto & Localização**, **Quotas & Pagamentos** e **Redes Sociais**.',
        minutes: 3,
        audience: 'direcao',
        tab: 'settings',
        relatedTabs: ['member-quotas'],
        related: ['socios-quotas', 'identidade-textos'],
        keywords: ['contactos', 'telefone', 'morada', 'mapa', 'horário', 'mb way', 'iban', 'multibanco', 'valor da quota', 'redes sociais', 'facebook', 'instagram', 'mandato'],
        steps: [
            { text: 'Em **Definições** › **Contacto & Localização**, preencha telefone, morada, horário e o link do Google Maps.' },
            { text: 'Em **Quotas & Pagamentos**, indique o **Valor da Quota**.' },
            { text: 'Ainda aí, preencha as formas de pagamento: MB WAY, IBAN ou Multibanco.', why: 'Estes dados só aparecem aos sócios com sessão iniciada, nunca a visitantes.' },
            { text: 'Em **Redes Sociais**, preencha **Facebook Page ID** e **Instagram (URL)**.', tip: 'Não sabe o ID da página de Facebook? Peça-o a quem gere a página.' },
            { text: 'Carregue em **Guardar alterações**.' },
        ],
    },
];

export const ASSISTANT_TUTORIALS: HelpTutorial[] = [
    {
        id: 'assistente-configurar',
        category: 'assistente',
        title: 'Configurar o assistente virtual',
        summary: 'Ligar o chat do site e experimentá-lo antes de o mostrar a todos.',
        recap: 'Em **Assistente virtual**, ligue **Chatbot Ativo**, guarde e experimente em **Abrir Chat de Teste**.',
        minutes: 3,
        audience: 'direcao',
        tab: 'ai',
        related: ['assistente-guardrails', 'ia-custos-orcamento', 'ia-motor-custos'],
        keywords: ['assistente', 'chatbot', 'chat', 'ia', 'fornecedor', 'modelo', 'openrouter', 'gemini', 'testar', 'bolha'],
        media: [image('assistente', 'Separador Assistente virtual com o fornecedor de IA e a configuração do chatbot')],
        steps: [
            { text: 'Abra **Assistente virtual**. Em **Fornecedor de IA** está o serviço usado; por omissão, o Google Gemini.', tip: 'Não mude o fornecedor nem os modelos sem falar com a equipa técnica.' },
            { text: 'Em **Configuração do Chatbot**, ligue **Chatbot Ativo**.' },
            { text: 'Quer o botão do chat em todas as páginas? Ligue **Mostrar Bolha Flutuante**.' },
            { text: 'Opcional: escreva **Instruções extra do sistema**, como "lembra sempre o horário da secretaria".' },
            { text: 'Carregue em **Guardar alterações**.' },
            { text: 'Em **Testar Chatbot**, carregue em **Abrir Chat de Teste** e faça uma pergunta.', why: 'O assistente responde com os dados reais do site: quanto mais atualizado, melhores as respostas.' },
        ],
    },
    {
        id: 'assistente-guardrails',
        category: 'assistente',
        title: 'Limites do assistente (guardrails)',
        summary: 'Os temas sobre os quais o assistente fala e os que recusa.',
        recap: 'Em **Guardrails & Segurança**, deixe **Guardrails Ativos** ligado e liste os temas permitidos e proibidos.',
        minutes: 2,
        audience: 'direcao',
        tab: 'ai',
        related: ['assistente-configurar', 'ia-custos-orcamento'],
        keywords: ['guardrails', 'segurança', 'tópicos permitidos', 'tópicos proibidos', 'limites', 'política'],
        steps: [
            { text: 'Em **Assistente virtual** › **Guardrails & Segurança**, deixe ligado **Guardrails Ativos**.', why: 'Evita que o chat do site fale de assuntos que nada têm a ver com a associação.' },
            { text: 'Em **Tópicos permitidos**, escreva os temas da associação, separados por vírgulas.' },
            { text: 'Em **Tópicos proibidos**, escreva o que deve ser recusado, como política partidária.' },
            { text: 'Carregue em **Guardar alterações**.', tip: 'Em **Utilização e custos**, no topo da página, vê os pedidos feitos ao assistente.' },
        ],
    },
];

export const PRACTICE_TUTORIALS: HelpTutorial[] = [
    {
        id: 'imagens-leves',
        category: 'boas-praticas',
        title: 'Imagens leves e bonitas',
        summary: 'Fotografias que carregam depressa no telemóvel de quem visita.',
        recap: 'JPG, PNG ou WebP até 10 MB, boa luz, 20 a 40 fotos por álbum; o site reduz o resto.',
        minutes: 2,
        audience: 'direcao',
        relatedTabs: ['gallery', 'news', 'events'],
        related: ['galeria-album', 'publicar-noticia'],
        keywords: ['imagens', 'fotografias', 'tamanho', 'pesado', 'lento', 'mb', 'qualidade', 'horizontal', 'vertical'],
        steps: [
            { text: 'Use JPG, PNG ou WebP até 10 MB.', why: 'O site reduz as imagens ao carregar, por isso não precisa de as encolher antes.' },
            { text: 'Para capas de notícias, prefira fotografias horizontais; para cartazes, verticais.' },
            { text: 'Fotografe com boa luz e sem zoom digital.', why: 'Uma foto nítida vale mais do que dez tremidas.' },
            { text: 'Escolha 20 a 40 fotos por álbum.', tip: 'Peça autorização antes de publicar fotos em que se reconheçam crianças.' },
        ],
    },
    {
        id: 'partilhar-redes',
        category: 'boas-praticas',
        title: 'Partilhar no WhatsApp e no Facebook',
        summary: 'Levar as pessoas ao site, onde se inscrevem e veem tudo.',
        recap: 'Publique no site primeiro e partilhe o link, não só a imagem do cartaz.',
        minutes: 2,
        audience: 'direcao',
        relatedTabs: ['events', 'news'],
        related: ['partilhar-evento', 'avisos-socios'],
        keywords: ['partilhar', 'whatsapp', 'facebook', 'divulgação', 'redes sociais', 'grupo', 'link'],
        steps: [
            { text: 'Publique primeiro no site e partilhe o link, em vez de enviar só o cartaz.', why: 'Quem abre o link vê tudo e inscreve-se logo; uma imagem não leva a lado nenhum.' },
            { text: 'Na página do evento ou da notícia, carregue em **WhatsApp**, **Facebook** ou **Copiar link**.' },
            { text: 'No WhatsApp, envie para os grupos da associação e peça para reencaminharem.' },
            { text: 'Volte a partilhar uns dias antes do evento, lembrando os lugares que restam.' },
        ],
    },
    {
        id: 'rgpd-basico',
        category: 'boas-praticas',
        title: 'Dados pessoais (RGPD) em termos simples',
        summary: 'O que a direção pode e não pode fazer com os dados dos sócios e participantes.',
        recap: 'Use os dados só para o que foram pedidos, escreva em Bcc e apague as listas depois do evento.',
        minutes: 3,
        audience: 'direcao',
        relatedTabs: ['registrations', 'member-quotas', 'access'],
        related: ['gerir-inscricoes', 'mudar-tipo-remover'],
        keywords: ['rgpd', 'dados pessoais', 'privacidade', 'proteção de dados', 'emails', 'apagar dados', 'consentimento'],
        steps: [
            { text: 'Use os dados de uma inscrição só para esse evento.', why: 'Juntá-los a listas de divulgação exige autorização de cada pessoa.' },
            { text: 'Ao escrever a vários participantes, ponha os endereços em Bcc.' },
            { text: 'Guarde as listas exportadas num sítio com palavra-passe e apague-as depois do evento.', tip: 'As inscrições sem conta apagam-se sozinhas 90 dias depois do evento; as canceladas, ao fim de 30.' },
            { text: 'Alguém pediu para ver ou apagar os seus dados? Faça-o e responda.', tip: 'A página **Privacidade** do site explica isto aos visitantes.' },
            { text: 'Dê acesso de administrador só a quem precisa e retire-o quando sai da direção.' },
        ],
    },
];
