import { image, video } from './media';
import type { HelpTutorial } from './types';

export const SETTINGS_TUTORIALS: HelpTutorial[] = [
    {
        id: 'identidade-textos',
        category: 'marca',
        title: 'Nome, textos e fotografia da página inicial',
        summary: 'A identidade da {siteName} que aparece em todo o site.',
        minutes: 3,
        audience: 'direcao',
        tab: 'settings',
        keywords: ['definições', 'nome', 'identidade', 'textos', 'hero', 'fotografia de fundo', 'sede', 'localidade', 'ano de fundação', 'logótipo'],
        steps: [
            { text: 'Abra "Definições". Em "Geral" ficam o "Nome do Site", o email e o "URL do logótipo".' },
            { text: 'Em "Identidade & Textos" carregue a "Fotografia de fundo da página inicial" e preencha nome completo, localidade, ano de fundação, tagline e subtítulo.' },
            { text: 'Ainda aí ficam a sede e os textos da página História. Campos vazios escondem a secção respetiva no site.' },
            { text: 'Em "Página Sobre" escreva a missão e os pilares da associação.' },
            { text: 'Carregue em "Guardar alterações", no fundo da página.', warning: 'Nada muda no site enquanto não guardar.' },
        ],
    },
    {
        id: 'mudar-marca',
        category: 'marca',
        title: 'Mudar a cor e a letra do site',
        summary: 'Uma cor e duas letras; o contraste fica garantido automaticamente.',
        minutes: 2,
        audience: 'direcao',
        tab: 'settings',
        featured: true,
        keywords: ['marca', 'cor', 'cor da marca', 'letra', 'fonte', 'tipografia', 'guia de marca', 'media kit', 'contraste'],
        media: [
            video('mudar-marca', 'Em Definições, na secção Marca, escolhe-se uma das cores sugeridas e depois a letra dos títulos. A pré-visualização ao lado e os rácios de contraste atualizam-se de imediato.'),
            image('marca', 'Secção Marca com cor, cores sugeridas, contraste, letras e pré-visualização'),
        ],
        steps: [
            { text: 'Em "Definições", desça até "Marca".' },
            { text: 'Em "Cor da marca", escolha uma das "Cores sugeridas", use o seletor ou escreva o código (#rrggbb) do logótipo.' },
            { text: 'Veja o quadro "Contraste": cores muito claras são escurecidas automaticamente nos botões e links, para continuarem legíveis.' },
            { text: 'Escolha a "Letra dos títulos" e a "Letra do texto". A "Pré-visualização" mostra o resultado.' },
            { text: 'Se a associação tiver um guia de marca, cole o link em "Guia de marca / media kit (link)": aparece "Marca e imprensa" no rodapé.' },
            { text: 'Carregue em "Guardar alterações".' },
        ],
    },
    {
        id: 'contactos-pagamentos',
        category: 'marca',
        title: 'Contactos, quotas e dados de pagamento',
        summary: 'Telefone, morada, mapa e as formas de pagar a quota.',
        minutes: 2,
        audience: 'direcao',
        tab: 'settings',
        relatedTabs: ['member-quotas'],
        keywords: ['contactos', 'telefone', 'morada', 'mapa', 'horário', 'mb way', 'iban', 'multibanco', 'valor da quota', 'redes sociais', 'facebook', 'instagram'],
        steps: [
            { text: 'Em "Definições", na secção "Contacto & Localização", preencha telefone, morada, horário e o link do Google Maps.' },
            { text: 'Em "Quotas & Pagamentos", indique o "Valor da Quota" e as formas de pagamento: MB WAY, IBAN ou Multibanco.', tip: 'Estes dados só aparecem aos sócios com sessão iniciada, nunca a visitantes.' },
            { text: 'Em "Redes Sociais", junte a página de Facebook e o Instagram.' },
            { text: 'Carregue em "Guardar alterações".' },
        ],
    },
];

export const ASSISTANT_TUTORIALS: HelpTutorial[] = [
    {
        id: 'assistente-configurar',
        category: 'assistente',
        title: 'Configurar o assistente virtual',
        summary: 'Ligar o chat do site, escolher o fornecedor e os modelos.',
        minutes: 3,
        audience: 'direcao',
        tab: 'ai',
        keywords: ['assistente', 'chatbot', 'chat', 'ia', 'fornecedor', 'modelo', 'openrouter', 'gemini', 'testar'],
        media: [image('assistente', 'Separador Assistente virtual com o fornecedor de IA e a configuração do chatbot')],
        steps: [
            { text: 'Abra "Assistente virtual". Em "Fornecedor de IA" fica o serviço usado pelo chat; por omissão, o Google Gemini.' },
            { text: 'Em "Configuração do Chatbot", ligue "Chatbot Ativo" e, se quiser o botão flutuante em todas as páginas, "Mostrar Bolha Flutuante".' },
            { text: 'Escolha o "Tom do Conteúdo" e, se precisar, escreva "Instruções extra do sistema" (por exemplo, "lembra sempre o horário da secretaria").' },
            { text: 'Carregue em "Guardar alterações" e experimente em "Testar Chatbot".', tip: 'O assistente responde com os dados reais do site: eventos, notícias, equipa e contactos. Manter o site atualizado melhora as respostas.' },
        ],
    },
    {
        id: 'assistente-guardrails',
        category: 'assistente',
        title: 'Limites do assistente (guardrails)',
        summary: 'Os temas sobre os quais o assistente fala e os que recusa.',
        minutes: 2,
        audience: 'direcao',
        tab: 'ai',
        keywords: ['guardrails', 'segurança', 'tópicos permitidos', 'tópicos proibidos', 'limites', 'política'],
        steps: [
            { text: 'Em "Guardrails & Segurança", deixe ligado "Guardrails Ativos".' },
            { text: 'Em "Tópicos permitidos", escreva os temas da associação, separados por vírgulas.' },
            { text: 'Em "Tópicos proibidos", escreva o que deve ser recusado com educação (por exemplo, política partidária).' },
            { text: 'Carregue em "Guardar alterações". Em "Utilização e custos" acompanha os pedidos feitos ao assistente.' },
        ],
    },
];

export const PRACTICE_TUTORIALS: HelpTutorial[] = [
    {
        id: 'imagens-leves',
        category: 'boas-praticas',
        title: 'Imagens leves e bonitas',
        summary: 'Fotografias que carregam depressa no telemóvel de quem visita.',
        minutes: 2,
        audience: 'direcao',
        relatedTabs: ['gallery', 'news', 'events'],
        keywords: ['imagens', 'fotografias', 'tamanho', 'pesado', 'lento', 'mb', 'qualidade', 'horizontal', 'vertical'],
        steps: [
            { text: 'Use JPG, PNG ou WebP até 10 MB. O site reduz as imagens automaticamente ao carregar.' },
            { text: 'Para capas de notícias, prefira fotografias horizontais; para cartazes, verticais.' },
            { text: 'Fotografe com boa luz e sem zoom digital: uma foto nítida vale mais do que dez tremidas.' },
            { text: 'Escolha 20 a 40 fotos por álbum. Muitas fotos parecidas cansam quem vê.', tip: 'Peça autorização antes de publicar fotos em que se reconheçam crianças.' },
        ],
    },
    {
        id: 'partilhar-redes',
        category: 'boas-praticas',
        title: 'Partilhar no WhatsApp e no Facebook',
        summary: 'Levar as pessoas ao site, onde se inscrevem e veem tudo.',
        minutes: 2,
        audience: 'direcao',
        relatedTabs: ['events', 'news'],
        keywords: ['partilhar', 'whatsapp', 'facebook', 'divulgação', 'redes sociais', 'grupo', 'link'],
        steps: [
            { text: 'Publique primeiro no site e partilhe o link, em vez de enviar só a imagem do cartaz.' },
            { text: 'Use os botões "WhatsApp" e "Facebook" da página do evento ou da notícia: a pré-visualização mostra a imagem e o título.' },
            { text: 'No WhatsApp, envie para os grupos da associação e peça para reencaminharem.' },
            { text: 'Repita a partilha uns dias antes do evento, lembrando os lugares que restam.' },
        ],
    },
    {
        id: 'rgpd-basico',
        category: 'boas-praticas',
        title: 'Dados pessoais (RGPD) em termos simples',
        summary: 'O que a direção pode e não pode fazer com os dados dos sócios e participantes.',
        minutes: 3,
        audience: 'direcao',
        relatedTabs: ['registrations', 'member-quotas', 'access'],
        keywords: ['rgpd', 'dados pessoais', 'privacidade', 'proteção de dados', 'emails', 'apagar dados', 'consentimento'],
        steps: [
            { text: 'Use os dados de uma inscrição só para esse evento. Não os junte a listas de divulgação sem autorização.' },
            { text: 'Ao escrever a vários participantes, ponha os endereços em Bcc.' },
            { text: 'Guarde as listas exportadas num sítio com palavra-passe e apague-as depois do evento.', tip: 'As inscrições feitas sem conta apagam-se sozinhas 90 dias depois do evento.' },
            { text: 'Se alguém pedir para ver ou apagar os seus dados, faça-o e responda. A página "Privacidade" do site explica tudo isto aos visitantes.' },
            { text: 'Dê acesso de administrador só a quem precisa e retire-o quando a pessoa sai da direção.' },
        ],
    },
];
