import { image } from './media';
import type { HelpTutorial } from './types';

export const START_TUTORIALS: HelpTutorial[] = [
    {
        id: 'primeiro-acesso',
        category: 'comecar',
        title: 'Primeiro acesso ao backoffice',
        summary: 'Entre com os dados que recebeu e fique com uma palavra-passe só sua.',
        recap: 'Entre em **Reservado** com o email e a palavra-passe temporária e mude-a logo a seguir.',
        minutes: 2,
        audience: 'direcao',
        tab: 'dashboard',
        featured: true,
        related: ['mudar-palavra-passe', 'percorrer-painel', 'resolver-problemas'],
        keywords: ['entrar', 'login', 'reservado', 'acesso reservado', 'palavra-passe temporária', 'primeira vez', 'backoffice'],
        steps: [
            { text: 'Abra o site da {siteName} e carregue em **Reservado**, no topo da página.', tip: 'No telemóvel, abra o menu e escolha **Acesso Reservado**.' },
            { text: 'Escreva o **Email** e a **Palavra-passe** temporária que lhe enviaram.', tip: 'Copie e cole a palavra-passe tal como veio: maiúsculas e minúsculas contam.' },
            { text: 'Carregue em **Entrar**. Abre-se o backoffice, na página **Início**.' },
            { text: 'No fundo do menu lateral, carregue em **Alterar palavra-passe** e escolha uma nova.', why: 'Quem tiver a mensagem com a palavra-passe temporária consegue entrar até a mudar.' },
        ],
    },
    {
        id: 'mudar-palavra-passe',
        category: 'comecar',
        title: 'Mudar a palavra-passe',
        summary: 'Troque a palavra-passe sempre que quiser, sem pedir a ninguém.',
        recap: 'Menu lateral › **Alterar palavra-passe**: a atual, a nova duas vezes e **Guardar**.',
        minutes: 1,
        audience: 'direcao',
        related: ['primeiro-acesso', 'repor-palavra-passe'],
        keywords: ['password', 'senha', 'alterar palavra-passe', 'segurança', 'conta', 'mudar'],
        steps: [
            { text: 'No fundo do menu lateral, carregue em **Alterar palavra-passe**.' },
            { text: 'Em **Palavra-passe atual**, escreva a que usa hoje.' },
            { text: 'Escreva a nova em **Nova palavra-passe** e repita-a em **Confirmar nova palavra-passe**.', tip: 'Pelo menos 10 caracteres, com maiúsculas, minúsculas e um número. Uma frase curta, como "Sardinhas-em-Junho-24", é fácil de lembrar.' },
            { text: 'Carregue em **Guardar**.', why: 'As outras sessões abertas com a sua conta terminam: se alguém a usava sem autorização, perde o acesso.' },
        ],
    },
    {
        id: 'percorrer-painel',
        category: 'comecar',
        title: 'Uma volta pelo painel',
        summary: 'O que está em cada secção do menu e onde ver o que precisa de atenção.',
        recap: '**Início** mostra o que precisa de atenção; **Conteúdos** é o que aparece no site; **Sistema** é a configuração.',
        minutes: 3,
        audience: 'direcao',
        tab: 'dashboard',
        related: ['criar-evento', 'gerir-inscricoes', 'site-atualizado'],
        keywords: ['menu', 'início', 'dashboard', 'secções', 'onde fica', 'navegar', 'ver site', 'painel'],
        media: [image('painel-inicio', 'Página Início do backoffice com os números do site e as inscrições por confirmar')],
        steps: [
            { text: 'Em **Início** veja os números do site, o cartão **IA este mês** e as inscrições por confirmar.' },
            { text: 'Ainda em **Início**, o cartão **Plataforma** diz se o site está na versão mais recente.' },
            { text: 'Em **Conteúdos** fica tudo o que aparece no site: eventos, notícias, galeria, sócios e mensagens.', tip: 'O número amarelo ao lado de **Inscrições** diz quantas esperam confirmação.' },
            { text: 'Em **Sistema** ficam documentos, avisos, acessos, o **Assistente virtual** e as **Definições**.' },
            { text: 'Em cada lista, pesquise (tecla /) e use **Duplicar**, **Editar** ou **Apagar** em cada linha.' },
            { text: 'Carregue em **Ver site**, no canto superior direito, para confirmar o resultado noutro separador.' },
            { text: 'Tem dúvidas numa secção? Carregue em **Como funciona**, ao lado do título.', tip: 'Todos os guias estão em **Ajuda**, no fundo do menu lateral.' },
        ],
    },
];
