import type { HelpTutorial } from './types';

export const SUPPORT_TUTORIALS: HelpTutorial[] = [
    {
        id: 'resolver-problemas',
        category: 'suporte',
        title: 'O que fazer se algo correr mal',
        summary: 'Os problemas mais comuns e como os resolver sem ajuda técnica.',
        recap: 'Quase tudo se resolve a recarregar a página ou a pedir uma palavra-passe nova a outro administrador.',
        minutes: 3,
        audience: 'direcao',
        relatedTabs: ['dashboard', 'registrations', 'settings', 'ai'],
        related: ['repor-palavra-passe', 'site-atualizado', 'gerir-inscricoes'],
        keywords: ['problema', 'erro', 'não funciona', 'avaria', 'não consigo entrar', 'imagem não muda', 'recarregar', 'inscrição desaparecida', 'saldo', 'openrouter', 'manutenção', 'suporte'],
        steps: [
            { text: 'Não consegue entrar? Peça a outro administrador uma **Nova palavra-passe**, em **Acessos**.', why: 'Por segurança, ninguém repõe a própria palavra-passe: tem de ser outra pessoa da direção.' },
            { text: 'Mudou uma imagem ou um texto e o site não mudou? Confirme que carregou em **Guardar**.' },
            { text: 'Guardou e continua igual? Recarregue a página.', tip: 'No computador, Ctrl + F5. No telemóvel, puxe a página para baixo.' },
            { text: 'Uma inscrição não aparece? Em **Inscrições**, confirme o evento escolhido em **Evento**.', tip: 'Use o filtro **Por confirmar** para ver só as que esperam resposta.' },
            { text: 'O cartaz saiu com NanoBanana e não com GPT Image? A conta OpenRouter ficou sem saldo.', why: 'O site troca de motor sozinho para não falhar. Carregue créditos em openrouter.ai para voltar ao GPT Image.' },
            { text: 'O site mostra **Portal em manutenção**? Desligue **Modo de Manutenção** em **Definições** › **Geral**.', tip: 'Os administradores veem o site normal; só os visitantes veem o aviso.' },
            { text: 'Depois de desligar, carregue em **Guardar alterações**.' },
            { text: 'Nada disto resolveu? Escreva à equipa técnica e junte uma captura de ecrã.', tip: 'Diga o que fez, o que esperava e a mensagem que apareceu: poupa várias trocas de emails.' },
        ],
    },
    {
        id: 'site-atualizado',
        category: 'suporte',
        title: 'Saber se o site está atualizado',
        summary: 'Onde ver a versão do site e o que fazer quando há uma nova.',
        recap: 'No rodapé, "atualizada" quer dizer que está tudo em dia; "disponível" quer dizer que há uma versão nova.',
        minutes: 1,
        audience: 'direcao',
        tab: 'dashboard',
        related: ['resolver-problemas', 'percorrer-painel'],
        keywords: ['versão', 'atualizado', 'atualização', 'atualizada', 'disponível', 'nova versão', 'plataforma', 'rodapé', 'novidades'],
        steps: [
            { text: 'Desça até ao fundo de qualquer página do site e procure a linha com a versão.' },
            { text: 'Se diz **atualizada**, o site tem a versão mais recente. Não precisa de fazer nada.' },
            { text: 'Se diz, por exemplo, **v2.19.0 disponível**, há uma versão nova.', tip: 'Carregue nesse texto para ler as novidades.' },
            { text: 'No backoffice, abra **Início** e veja o cartão **Plataforma**, na coluna da direita.' },
            { text: 'Aparece **Peça à equipa técnica para atualizar este site**? Encaminhe o aviso à equipa técnica.', why: 'A atualização é feita no servidor: a direção não precisa de instalar nada.' },
            { text: 'Aparece **Há uma versão mais recente publicada — recarregar**? Carregue nesse botão.', why: 'O site já foi atualizado; só a sua janela estava com a versão antiga.' },
        ],
    },
    {
        id: 'algo-nao-funciona',
        category: 'conta',
        title: 'Algo não funciona no site',
        summary: 'O que fazer quando não consegue entrar ou uma página não mostra o que esperava.',
        recap: 'Recarregue a página; se não conseguir entrar, peça uma palavra-passe nova à direção.',
        minutes: 1,
        audience: 'socio',
        related: ['esqueci-palavra-passe', 'contactar-direcao'],
        keywords: ['problema', 'erro', 'não funciona', 'não consigo entrar', 'manutenção', 'recarregar', 'página', 'ajuda'],
        steps: [
            { text: 'Não consegue entrar? Peça à direção da {siteName} uma palavra-passe nova.', why: 'Por segurança, só a direção consegue gerar uma palavra-passe nova.' },
            { text: 'A página não mostra o que esperava? Recarregue-a.', tip: 'No computador, Ctrl + F5. No telemóvel, puxe a página para baixo.' },
            { text: 'Aparece **Portal em manutenção**? Volte dentro de alguns minutos.' },
            { text: 'Não vê o seu número de sócio? Peça à direção para confirmar o email registado.' },
            { text: 'O problema continua? Carregue em **Contacte-nos**, no fim da página, e explique o que aconteceu.' },
        ],
    },
];
