import type { MutationCtx } from "../_generated/server";
import type { Id } from "../_generated/dataModel";

/**
 * Ledger of files uploaded through the admin MediaStudio (or generated by the image AI).
 *
 * Those files reach the records as plain URLs in the external* fields, so without a ledger
 * nothing knows which stored file a URL points to and a replaced image stays in storage
 * forever. Each row counts the records that use the URL: saving a record retains it, replacing
 * or deleting releases it, and the file goes when nothing uses it any more. A duplicated record
 * simply holds a second reference. Rows nobody retained are abandoned uploads (a form closed
 * without saving, a second pick before saving) and the daily sweep removes them.
 */

/** How long an upload may wait for a save before the sweep treats it as abandoned. */
export const ABANDONED_UPLOAD_MS = 48 * 3600 * 1000;

async function findByUrl(ctx: MutationCtx, url: string) {
  return await ctx.db.query("uploads").withIndex("by_url", (q) => q.eq("url", url)).first();
}

/** Idempotent: registering a URL twice must not reset the references a record already holds. */
export async function registerUpload(ctx: MutationCtx, storageId: Id<"_storage">, url: string) {
  if (await findByUrl(ctx, url)) return;
  await ctx.db.insert("uploads", { storageId, url, refs: 0, createdAt: Date.now() });
}

async function dropUpload(ctx: MutationCtx, row: { _id: Id<"uploads">; storageId: Id<"_storage"> }) {
  try { await ctx.storage.delete(row.storageId); } catch (e) { console.error("Failed to delete storage:", e); }
  await ctx.db.delete(row._id);
}

/** A record now uses `url`. URLs that are not uploads (typed links, legacy files) are ignored. */
export async function retainUrl(ctx: MutationCtx, url: unknown) {
  if (typeof url !== "string" || !url) return;
  const row = await findByUrl(ctx, url);
  if (row) await ctx.db.patch(row._id, { refs: row.refs + 1 });
}

/** A record stopped using `url`; the file goes with its last reference. */
export async function releaseUrl(ctx: MutationCtx, url: unknown) {
  if (typeof url !== "string" || !url) return;
  const row = await findByUrl(ctx, url);
  if (!row) return;
  if (row.refs <= 1) await dropUpload(ctx, row);
  else await ctx.db.patch(row._id, { refs: row.refs - 1 });
}

/** Retain before release, so swapping a URL for itself never deletes the file. */
export async function swapUrl(ctx: MutationCtx, previous: unknown, next: unknown) {
  if (previous === next) return;
  await retainUrl(ctx, next);
  await releaseUrl(ctx, previous);
}

/**
 * Drops an upload no record holds yet: the heavy original of an image the browser
 * re-optimised, or a reference picture that only fed the AI. A retained URL is
 * left alone, so a stale call can never delete a file a record uses.
 */
export async function discardUnretained(ctx: MutationCtx, url: string): Promise<boolean> {
  const row = await findByUrl(ctx, url);
  if (!row || row.refs > 0) return false;
  await dropUpload(ctx, row);
  return true;
}

/** Remove uploads nobody saved within the grace period. Returns how many went. */
export async function sweepAbandonedUploads(ctx: MutationCtx, now: number, limit = 200) {
  const stale = await ctx.db
    .query("uploads")
    .withIndex("by_refs_created", (q) => q.eq("refs", 0).lt("createdAt", now - ABANDONED_UPLOAD_MS))
    .take(limit);
  for (const row of stale) await dropUpload(ctx, row);
  return stale.length;
}
